{% set name = "easysnowdata" %}
{% set version = "0.2.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/easysnowdata-{{ version }}.tar.gz
  sha256: 1b01cdb16f32a56f576a4b102cde099359db1df0e2222c32cda504ee89a83ea6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.27
    - hatch-vcs >=0.4
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - pandas
    - geopandas >=1.1
    - pyogrio >=0.12
    - pyarrow
    - pyproj
    - rasterio >=1.5
    - xarray >=2026.2
    - rioxarray >=0.22
    - shapely >=2
    - pystac >=1.12
    - pystac-client >=0.8
    - planetary-computer
    - odc-stac >=0.5
    - odc-geo >=0.5
    - earthengine-api
    - xee >=0.1
    - beautifulsoup4
    - earthaccess >=0.17
    - planet >=3.6
    - pooch
    - pyyaml
    - requests
    - lxml
    - scikit-image
    - tqdm
    - dask-core
    - zarr >=3.1
    - gcsfs
    - s3fs
    - fsspec
    - h5netcdf
    - h5py

test:
  imports:
    - easysnowdata
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://egagli.github.io/easysnowdata/
  summary: A Python package to easily retrieve data relevant to snow science
  license: MIT
  license_file: LICENSE
  doc_url: https://egagli.github.io/easysnowdata
  dev_url: https://github.com/egagli/easysnowdata

extra:
  recipe-maintainers:
    - egagli
