{% set name = "easysnowdata" %}
{% set version = "0.0.18" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/easysnowdata-{{ version }}.tar.gz
  sha256: 176f536890b60f4fba52eaaa0b00bcac65e6d4387aeb804a180d1420ca15b863

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - pandas
    - geopandas
    - rasterio
    - xarray
    - rioxarray
    - shapely
    - pystac-client
    - planetary-computer
    - odc-stac
    - xee
    - beautifulsoup4
    - py3dep
    - earthaccess
    - contextily
    - folium
    - mapclassify
    - lxml
    - pytkdocs
    - scikit-image
    - pytest

test:
  imports:
    - easysnowdata
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://egagli.github.io/easysnowdata/
  summary: package to easily get data relevant to snow
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - egagli
